version: '3.5'

services:
  app:
    build:
      context: . #current directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - redis
    environment:
      REDIS_LOCAL_URL: "redis:6379" #the key is the same as the service name (redis)
    networks:
      - minesweepernetwork
  redis:
    image: redis
    networks:
      - minesweepernetwork
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      minesweepernetwork: # network to communicate containers with each other
      